name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar código
        uses: actions/checkout@v4

      - name: 2. Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 3. Instalar dependencias
        run: npm ci

      - name: 4. Compilar Angular
        run: npx ng build --configuration production --base-href /

      - name: 5. Arreglar rutas
        run: cp dist/inventory-frontend/browser/index.html dist/inventory-frontend/browser/404.html

      - name: 6. Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/inventory-frontend/browser
          cname: erp.saul-toscano.fyi